basePath: /
definitions:
  dto.LoginForm:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.SignUpForm:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  wrapper.CustomError:
    properties:
      err: {}
      statusCode:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: IT events platform
  title: Dev clash API
  version: "1.0"
paths:
  /api/check:
    get:
      consumes:
      - application/json
      description: Check current state of authorization
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Authorized
      tags:
      - api
  /api/events/create:
    post:
      consumes:
      - multipart/form-data
      description: Create event (users can't do it)
      parameters:
      - in: formData
        name: description
        type: string
      - in: formData
        name: end_time
        type: string
      - in: formData
        name: is_free
        type: boolean
      - in: formData
        name: is_online
        type: boolean
      - in: formData
        name: number_of_teams
        type: integer
      - in: formData
        name: prize
        type: string
      - in: formData
        name: start_time
        type: string
      - in: formData
        name: team_size
        type: integer
      - collectionFormat: csv
        in: formData
        items:
          type: string
        name: tech_stack
        type: array
      - in: formData
        name: title
        type: string
      - in: formData
        name: type
        type: string
      - description: Event picture
        in: formData
        name: picture
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Create event
      tags:
      - event
  /api/image:
    get:
      consumes:
      - application/json
      description: Generates a presigned URL for accessing an image stored in S3
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Get S3 Image URL
      tags:
      - s3
  /api/logout:
    post:
      consumes:
      - application/json
      description: Refreshes TokenPair and check refresh token is consumed or not
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Logout
      tags:
      - user
  /api/organizers/{id}:
    get:
      consumes:
      - application/json
      description: Get organizer profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Organizer Profile
      tags:
      - organizer
  /api/teams/create:
    post:
      consumes:
      - multipart/form-data
      description: Create team
      parameters:
      - description: Team name
        in: formData
        name: name
        required: true
        type: string
      - description: Team status
        in: formData
        name: team_status
        type: string
      - description: Team description
        in: formData
        name: description
        type: string
      - description: Team picture
        in: formData
        name: picture
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Create team
      tags:
      - team
  /api/users/me/profile:
    get:
      consumes:
      - application/json
      description: Get current user profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Profile
      tags:
      - user
  /api/users/me/settings:
    get:
      consumes:
      - application/json
      description: Get current user profile settings
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Profile settings
      tags:
      - user
  /api/users/me/update:
    put:
      description: Update current user profile
      parameters:
      - in: formData
        name: description
        type: string
      - in: formData
        name: end_time
        type: string
      - in: formData
        name: is_free
        type: boolean
      - in: formData
        name: is_online
        type: boolean
      - in: formData
        name: number_of_teams
        type: integer
      - in: formData
        name: prize
        type: string
      - in: formData
        name: start_time
        type: string
      - in: formData
        name: team_size
        type: integer
      - collectionFormat: csv
        in: formData
        items:
          type: string
        name: tech_stack
        type: array
      - in: formData
        name: title
        type: string
      - in: formData
        name: type
        type: string
      - description: Event picture
        in: formData
        name: picture
        required: true
        type: file
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Update user
      tags:
      - user
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return access + refresh tokenss
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Login
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refreshes TokenPair and check refresh token is consumed or not
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Refresh
      tags:
      - auth
  /auth/signup/organizer:
    post:
      consumes:
      - multipart/form-data
      description: Create a new organizer account with logo upload
      parameters:
      - description: Organizer email
        in: formData
        name: email
        required: true
        type: string
      - description: Organizer name
        in: formData
        name: name
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Brand color
        in: formData
        name: color
        required: true
        type: string
      - description: Organizer logo
        in: formData
        name: logo
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "413":
          description: Request Entity Too Large
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Register a new organizer
      tags:
      - auth
  /auth/signup/user:
    post:
      consumes:
      - application/json
      description: Creates a user in database
      parameters:
      - description: Signup credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Sign Up User
      tags:
      - auth
securityDefinitions:
  CookieAuth:
    description: JWT access token stored in HttpOnly cookie named `access`
    in: cookie
    name: access
    type: apiKey
swagger: "2.0"
