basePath: /
definitions:
  dto.LoginForm:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.SignUpForm:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  wrapper.CustomError:
    properties:
      err: {}
      statusCode:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: IT events platform
  title: Dev clash API
  version: "1.0"
paths:
  /api/image:
    get:
      consumes:
      - application/json
      description: Generates a presigned URL for accessing an image stored in S3
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Get S3 Image URL
      tags:
      - s3
  /api/logout:
    post:
      consumes:
      - application/json
      description: Refreshes TokenPair and check refresh token is consumed or not
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Logout
      tags:
      - user
  /api/organizers/{id}:
    get:
      consumes:
      - application/json
      description: Get current user profile settings
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Organizer Profile
      tags:
      - organizer
  /api/teams/create:
    post:
      consumes:
      - multipart/form-data
      description: Get current user profile settings
      parameters:
      - description: Team name
        in: formData
        name: name
        required: true
        type: string
      - description: Team status
        in: formData
        name: team_status
        type: string
      - description: Team description
        in: formData
        name: description
        type: string
      - description: Team picture
        in: formData
        name: picture
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Organizer Profile
      tags:
      - team
  /api/users/me/profile:
    get:
      consumes:
      - application/json
      description: Get current user profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Profile
      tags:
      - user
  /api/users/me/settings:
    get:
      consumes:
      - application/json
      description: Get current user profile settings
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      security:
      - CookieAuth: []
      summary: Profile settings
      tags:
      - user
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return access + refresh tokenss
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Login
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refreshes TokenPair and check refresh token is consumed or not
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Refresh
      tags:
      - auth
  /auth/signup/organizer:
    post:
      consumes:
      - multipart/form-data
      description: Create a new organizer account with logo upload
      parameters:
      - description: Organizer email
        in: formData
        name: email
        required: true
        type: string
      - description: Organizer name
        in: formData
        name: name
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Brand color
        in: formData
        name: color
        required: true
        type: string
      - description: Organizer logo
        in: formData
        name: logo
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Register a new organizer
      tags:
      - auth
  /auth/signup/user:
    post:
      consumes:
      - application/json
      description: Creates a user in database
      parameters:
      - description: Signup credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/dto.SignUpForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/wrapper.CustomError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/wrapper.CustomError'
      summary: Sign Up User
      tags:
      - auth
securityDefinitions:
  CookieAuth:
    description: JWT access token stored in HttpOnly cookie named `access`
    in: cookie
    name: access
    type: apiKey
swagger: "2.0"
